config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords"
  }

  resources :users, only: [ :show, :edit, :update ] do
    resources :cats, only: [ :new, :create, :edit, :update, :show, :destroy ]
  end

  resources :cats, only: [ :index ]

  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  post "logout", to: "sessions#destroy", as: "logout"

  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "terms_of_service" => "terms_of_service#index"
  get "privacy_policies" => "privacy_policies#index"
  get "images/ogp.png", to: "images#ogp", as: "images_ogp"



  resources :feeding_calculation, only: [ :new ] do
    collection do
      post :calculate # 計算を行う
      post :save      # 結果を保存 (ログインユーザーのみ)
      get :calculate
    end
    member do
      delete :destroy
    end
  end

  resources :brands, only: [ :index, :show ] do
    member do
      get :foods # /brands/:id/foods に対応
    end

    collection do
      get :autocomplete
    end
  end



  resources :foods, only: [ :show ] do
    collection do
      get :bookmarks
    end

    resources :reviews, only: [ :new, :create ]
  end

  # resources :reviews, only: [ :index ]

  resources :bookmarks, only: [ :create, :destroy ]

  resources :contacts, only: [ :new, :create ] do
    collection do
      match "confirm", via: [ :get, :post ]
      post "back"
      get "done"
    end
  end

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [ :google_oauth2 ]

  enum role: { general: 0, admin: 1 } # 役割の定義

  has_many :cats, dependent: :destroy
  has_many :review, dependent: :destroy
  has_many :helpful, dependent: :destroy
  has_many :feeding_calculations, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_foods, through: :bookmarks, source: :food
  has_one_attached :profile

  validates :name, presence: true, length: { in: 1..10 }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, if: -> { password.present? }
  validates :self_introduction, length: { in: 0..250 }, allow_blank: true
  validates :uid, uniqueness: { scope: :provider }, allow_nil: true

  def bookmark(food)
    bookmark_foods << food
  end

  def unbookmark(food)
    bookmarks.find_by(food_id: food.id)&.destroy
  end

  def bookmark?(food)
    bookmark_foods.include?(food)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0, 20]

      # プロフィール画像をアタッチする
      # user.profile.attach(io: URI.open(auth.info.image), filename: 'profile.jpg', content_type: 'image/jpeg')
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # callback for google
  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    # 先ほどuser.rbで記述したメソッド(from_omniauth)をここで使っています
    # 'request.env["omniauth.auth"]'この中にgoogoleアカウントから取得したメールアドレスや、名前と言ったデータが含まれています
    auth = request.env["omniauth.auth"]
    Rails.logger.debug "OAuth auth response: #{auth.inspect}" # 追加

    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user, event: :authentication
    set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_user, only: [ :edit, :update ]
  def show
    @user = User.find(params[:id])
    @cats = @user.cats.order(created_at: :desc)
    if current_user
      @calculation_result = current_user.feeding_calculations.includes(:main_food).order(created_at: :desc)
    else
      @calculation_result = [] # 適当なデフォルト値を設定
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user, notice: "ユーザー情報が更新されました"
    else
      flash.now[:alert] = @user.errors.full_messages.join(", ")
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :self_introduction, :profile)
  end

  def authorize_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path, alert: "権限がありません"
    end
  end
end

app/views/users/edit.html.erb
<h1 class="text-center mb-6 mt-2 text-2xl text-default">ユーザープロフィール編集</h1>

<div class="flex items-center justify-center">
  <div class="w-full max-w-2xl bg-white p-8 rounded-lg shadow-md">
    <%= form_with(model: @user, method: :patch, data: { turbo: false }, class: "space-y-6") do |f| %>
      <div>
        <%= f.label :name, class: "block text-lg font-medium text-gray-700" %>
        <%= f.text_field :name, placeholder: "10文字まで", class: "mt-2 w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>
      <div>
        <h2 class="text-lg font-medium text-gray-700">プロフィール画像</h2>
        <%= f.file_field :profile, class: "mt-2 block w-full text-gray-700 border border-gray-300 rounded-lg cursor-pointer bg-white focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>
      <div>
        <%= f.label :self_introduction, class: "block text-lg font-medium text-gray-700" %>
        <%= f.text_area :self_introduction, placeholder: "250文字まで", class: "mt-2 w-full h-32 px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>
      <div class="flex justify-center">
        <%= f.submit '更新する', class: "w-full sm:w-auto px-6 py-2 text-lg font-semibold text-white bg-blue-500 rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 shadow-md" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="flex flex-col items-center">
  <h1 class="text-3xl mb-6 mt-2 text-center text-default">ユーザーページ</h1>

  <!-- コンテンツを中央に配置 -->
  <div class="w-full rounded-lg p-2 sm:mb-2 mx-auto text-center">
    <div class="bg-white w-[300px] p-5 mb-6 text-center mx-auto">
      <%= image_tag @user.profile.attached? ? @user.profile : 'account.png', class: 'w-14 h-14 rounded-full object-cover border border-default mx-auto' %>
      <div class="text-4xl">
        <p><%= @user.name %></p>
      </div>
      <div class="bg-gray-50 text-sm mb-5 p-5">
        <p><%= @user.self_introduction %></p>
      </div>
      <% if @user == current_user %>
        <div class="flex justify-center">
          <%= link_to edit_user_path, class: "flex items-center bg-blue-500 text-white py-2 px-4 rounded shadow hover:bg-blue-600 transition duration-200" do %>
            <span class="material-icons">edit</span>
            <span class="ml-1">編集</span>
          <% end %>
        </div>
      <% end %>
    </div>

    <% if @user == current_user %>
      <div class="flex justify-center mt-4 text-center pb-6">
        <%= link_to new_user_cat_path(current_user), class: 'flex justify-center w-1/2 px-4 py-2 bg-default text-2xl text-white rounded-md hover:opacity-50' do %>
          <span class="material-icons mt-1">add_circle</span>
          <span class="ml-1">ペットを登録</span>
        <% end %>
      </div>
    <% end %>

    <h2 class="text-2xl mb-4 my-4 text-default">登録済みペット</h2>

    <!-- cat_card の表示 -->
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
      <%= render partial: "shared/cat_card", collection: @cats, as: :cat %>
    </div>

    <div class="border-t border-gray-300 mt-6">
      <% if @user == current_user %>
        <% if @calculation_result.present? %>
          <h2 class="text-2xl mb-4 mt-2 text-default">計算結果一覧</h2>
          <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-4 gap-6">
            <% @calculation_result.each do |calculation| %>
              <div class="bg-white content w-full mx-auto p-6 rounded-lg shadow-md">
                <div class="text-left space-y-1">
                  <div class="flex flex-col">
                    <span class="text-sm text-gray-600">メインフード メーカー名</span>
                    <strong class="text-lg text-gray-900"><%= calculation.main_brand.name %></strong>
                  </div>
                  <div class="flex flex-col">
                    <span class="text-sm text-gray-600">メインフード フード名</span>
                    <strong class="text-lg text-gray-900"><%= calculation.main_food.name %></strong>
                  </div>
                  <div class="flex flex-col">
                    <span class="text-sm text-gray-600">サブフード メーカー名</span>
                    <strong class="text-lg text-gray-900"><%= calculation.sub_brand&.name.presence || 'なし' %></strong>
                  </div>
                  <div class="flex flex-col">
                    <span class="text-sm text-gray-600">サブフード フード名</span>
                    <strong class="text-lg text-gray-900"><%= calculation.sub_food&.name.presence || 'なし' %></strong>
                  </div>
                  <div class="flex flex-col">
                    <span class="text-sm text-gray-600">体重</span>
                    <div class="flex items-center text-lg text-gray-900">
                      <strong><%= calculation.weight %></strong>
                      <span class="ml-1 text-sm text-gray-600">kg</span>
                    </div>
                  </div>
                  <div class="flex flex-col">
                    <span class="text-sm text-gray-600">メインフードの1日の必要給与量</span>
                    <div class="flex items-center text-lg text-gray-900">
                      <strong><%= calculation.main_food_amount %></strong>
                      <span class="ml-1 text-sm text-gray-600">g</span>
                    </div>
                  </div>
                  <div class="flex flex-col">
                    <span class="text-sm text-gray-600">サブフードの1日の必要給与量</span>
                    <div class="flex items-center text-lg text-gray-900">
                      <strong><%= calculation.sub_food_amount %></strong>
                      <span class="ml-1 text-sm text-gray-600">g</span>
                    </div>
                  </div>
                  <div class="flex flex-col">
                    <span class="text-sm text-gray-600">必要エネルギー要求量 (RER)</span>
                    <div class="flex items-center text-lg text-gray-900">
                      <strong><%= calculation.total_daily_calories %></strong>
                      <span class="ml-1 text-sm text-gray-600">kcal</span>
                    </div>
                  </div>
                  <div class="flex flex-col">
                    <span class="text-sm text-gray-600">作成日</span>
                    <div class="flex items-center text-lg text-gray-900">
                      <strong><%= calculation.created_at.strftime('%Y-%m-%d') %></strong>
                    </div>
                  </div>
                  <div class="flex justify-center mt-4">
                    <%= button_to '削除', feeding_calculation_path(calculation.id), method: :delete, 
                          class: 'bg-red-500 hover:bg-red-600 text-white py-2 px-6 rounded-lg shadow' %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% else %>
          <p class="bg-white shadow-md text-red-500 p-4 rounded-md mt-4 w-full max-w-2xl mx-auto text-center">
            計算結果はまだありません。
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>