config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords"
  }

  resources :users, only: [ :show, :edit, :update ] do
    resources :cats, only: [ :new, :create, :edit, :update, :show, :destroy ]
  end

  resources :cats, only: [ :index ]

  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  post "logout", to: "sessions#destroy", as: "logout"

  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "terms_of_service" => "terms_of_service#index"
  get "privacy_policies" => "privacy_policies#index"
  get "images/ogp.png", to: "images#ogp", as: "images_ogp"



  resources :feeding_calculation, only: [ :new ] do
    collection do
      post :calculate # 計算を行う
      post :save      # 結果を保存 (ログインユーザーのみ)
      get :calculate
    end
    member do
      delete :destroy
    end
  end

  resources :brands, only: [ :index, :show ] do
    member do
      get :foods # /brands/:id/foods に対応
    end

    collection do
      get :autocomplete
    end
  end



  resources :foods, only: [ :show ] do
    collection do
      get :bookmarks
    end

    resources :reviews, only: [ :new, :create ]
  end

  # resources :reviews, only: [ :index ]

  resources :bookmarks, only: [ :create, :destroy ]

  resources :contacts, only: [ :new, :create ] do
    collection do
      match "confirm", via: [ :get, :post ]
      post "back"
      get "done"
    end
  end

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"
end

app/views/shared/_after_login_header.html.erb
<div class="bg-header">
  <header class="fixed top-0 left-0 w-full bg-header shadow-md z-50">
    <div class="navbar flex justify-between px-4 py-2">
      <!-- アプリタイトル -->
      <div class="flex-1">
        <%= link_to '/', class: 'block' do %>
          <%= image_tag 'logo.png', class:"transition duration-200 hover:opacity-40"%>
        <% end %>
      </div>
      <div class="flex-none">
        <div class="dropdown dropdown-end">
          <label tabindex="0" class="btn btn-ghost">
            メニュー
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 ml-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
            </svg>
          </label>
          <ul tabindex="0" class="dropdown-content z-50 menu p-2 shadow bg-base-100 rounded-box w-52">
            <li>
              <%= link_to user_path(current_user.id), class: "flex items-center space-x-2" do %>
                <span class="material-icons text-default">account_circle</span>
                <span>ユーザーページ</span>
              <% end %>
            </li>
            <li>
              <%= link_to bookmarks_foods_path, class: "flex items-center space-x-2" do %>
                <span class="material-icons text-default">bookmarks</span>
                <span>ブックマーク一覧</span>
              <% end %>
            </li>
            <div class="divider my-1"></div>
            <li>
              <%= link_to new_feeding_calculation_path, class: "flex items-center space-x-2" do %>
                <span class="material-icons text-default">calculate</span>
                <span>給与量の計算</span>
              <% end %>
            </li>
            <li>
              <%= link_to brands_path, class: "flex items-center space-x-2" do %>
                <span class="material-icons text-default">reviews</span>
                <span>フードレビュー</span>
              <% end %>
            </li>
            <li>
              <%= link_to cats_path, class: "flex items-center space-x-2" do %>
                <span class="material-icons text-default">pets</span>
                <span>みんなのペット</span>
              <% end %>
            </li>
            <div class="divider my-1"></div>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "flex items-center space-x-2" do %>
                <span class="material-icons text-default">logout</span>
                <span>ログアウト</span>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </header>
</div>

app/views/shared/_before_login_header.html.erb
<div class="bg-header">
  <header class="fixed top-0 left-0 w-full bg-header shadow-md z-50">
    <div class="navbar flex justify-between px-4 py-2">
      <!-- アプリタイトル -->
      <div class="flex-1">
        <%= link_to '/', class: 'block' do %>
          <%= image_tag 'logo.png', class:"transition duration-200 hover:opacity-40"%>
        <% end %>
      </div>

      <!-- メニュー -->
      <div class="flex-none">
        <div class="dropdown dropdown-end">
          <label tabindex="0" class="btn btn-ghost">
            メニュー
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 ml-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
            </svg>
          </label>
          <ul tabindex="0" class="dropdown-content z-50 menu p-2 shadow bg-base-100 rounded-box w-52">
            <li>
              <%= link_to new_user_session_path, class: "flex items-center space-x-2" do %>
                <span class="material-icons text-default">login</span>
                <span>ログイン</span>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class: "flex items-center space-x-2" do %>
                <span class="material-icons text-default">person_add</span>
                <span>新規登録</span>
              <% end %>
            </li>
            <div class="divider my-1"></div>
            <li>
              <%= link_to new_feeding_calculation_path, class: "flex items-center space-x-2" do %>
                <span class="material-icons text-default">calculate</span>
                <span>給与量の計算</span>
              <% end %>
            </li>
            <li>
              <%= link_to brands_path, class: "flex items-center space-x-2" do %>
                <span class="material-icons text-default">reviews</span>
                <span>フードレビュー</span>
              <% end %>
            </li>
            <li>
              <%= link_to cats_path, class: "flex items-center space-x-2" do %>
                <span class="material-icons text-default">pets</span>
                <span>みんなのペット</span>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </header>
</div>

app/views/shared/_cat_card.html.erb
<div class="bg-white shadow-lg rounded-lg overflow-hidden">
  <div class="relative w-full h-48">
    <%= link_to user_cat_path(cat.user, cat) do %>
      <%= image_tag(cat.cat_profile.attached? ? cat.cat_profile : 'pets.png', class: "w-full h-full transform hover:scale-105 duration-300 object-cover") %>
    <% end %>
  </div>
  <div class="p-4 content w-full max-w-xs mx-auto">
    <div class="flex items-left">
      <% user = cat.user %>
      <%= link_to image_tag(user.profile.attached? ? user.profile : 'account.png', class: 'w-10 h-10 rounded-full object-cover border border-default mr-3'), user_path(user) %>
      <%= link_to user.name, user_path(user), class: 'text-lg text-gray-800 mt-2 hover:underline', style: 'text-decoration-color: #3B82F6;' %>
    </div>
    <div class="text-left my-2">
      <h2 class="text-xl text-gray-900 truncate" title="<%= cat.name %>"><%= cat.name %></h2>
      <p class="text-l truncate" title="<%= cat.cat_introduction %>"><%= cat.cat_introduction %></p>
      <p class="text-sm text-gray-500">登録日: <%= cat.created_at.strftime('%Y-%m-%d') %></p>
    </div>
  </div>
</div>

app/views/shared/_food_card.html.erb
<div class="food-card p-4 bg-white shadow-md rounded-lg text-center flex flex-col h-full justify-center">
  <div class="flex-1 justify-center">
    <h3 class="text-lg font-semibold text-gray-800 break-words"><%= food.name %></h3>
    <p class="text-sm text-gray-600 mt-2"><%= food.brand.name %></p>
  </div>
  
  <div class="flex justify-center items-center mt-2 mb-4">
    <div class="flex">
      <% 5.times do |i| %>
        <% if i < food.average_rating.to_i %>
          <svg class="w-4 h-4 text-yellow-300 me-1" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
            <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
          </svg>
        <% else %>
          <svg class="w-4 h-4 text-gray-300 me-1" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
            <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
          </svg>
        <% end %>
      <% end %>
    </div>
    <p class="ms-1 text-sm font-medium text-gray-500"><%= food.average_rating %></p>
    <p class="ms-1 text-sm font-medium text-gray-500">/</p>
    <p class="ms-1 text-sm font-medium text-gray-500">5</p>
  </div>

  <div class="flex justify-center">
    <%= link_to '詳細', food_path(food), class: "w-1/2 px-4 py-2 text-sm text-white bg-default rounded hover:opacity-50" %>
  </div>
</div>

app/views/shared/_footer.html.erb
<!-- 未ログイン時のフッター -->
<footer id="footer" class="footer-bottom bg-light py-3" style="background-color: #8b4513; border-top: 1px solid #ddd; box-shadow: 0 -2px 5px rgba(0, 0, 0, 0.1);">
  <div class="mx-auto px-0">
    <div class="flex justify-between px-4">
      <div class="flex text-white space-x-4">
        <%= link_to 'お問い合わせ', new_contact_path, class: 'footer-link text-center text-sm md:text-base' %>
        <%= link_to '利用規約', terms_of_service_path, class: 'footer-link text-center text-sm sm:text-base' %>
        <%= link_to 'プライバシーポリシー', privacy_policies_path, class: 'footer-link text-center text-sm sm:text-base' %>
      </div>

      <!-- Twitter アイコンを右端に固定 -->
      <%= link_to "https://x.com/CatFoodMat45083", target: "_blank", class: "text-white" do %>
        <i class="fa-brands fa-x-twitter text-3xl"></i>
      <% end %>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<!-- 未ログイン状態のヘッダー -->
<header class="flex justify-between bg-amber-400 ">
  <div class="navbar container mx-auto">
    <!-- アプリタイトル -->
    <div class="flex-1">
      <%= link_to '/', class: 'btn btn-ghost normal-case text-xl' do %>
        Cat Food Mate
      <% end %>
    </div>

    <!-- メニュー -->
    <div class="flex-none">
      <div class="dropdown dropdown-end">
        <label tabindex="0" class="btn btn-ghost">
          メニュー
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 ml-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
          </svg>
        </label>
        <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
          <li><%= link_to 'ログイン', new_user_session_path %></li>
          <li><%= link_to '新規登録', new_user_registration_path %></li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_user_card.html.erb
<div class="bg-white w-[300px] p-5 text-center rounded-lg shadow-md">
  <%= image_tag @user.profile.attached? ? @user.profile : 'account.png', class: 'w-14 h-14 rounded-full object-cover border border-default mx-auto' %>
  <div class="font-bold">
    <p class="text-2xl"><%= @user.name %></p>
  </div>
  <div class="bg-gray-50 text-sm mb-5 p-5">
    <p><%= @user.self_introduction %></p>
  </div>
  <% if @user == current_user %>
    <div class="flex justify-center">
      <%= link_to edit_user_path, class: "flex items-center bg-blue-500 text-white py-2 px-4 rounded shadow hover:bg-blue-600 transition duration-200" do %>
        <span class="material-icons">edit</span>
        <span class="ml-1">編集</span>
      <% end %>
    </div>
  <% end %>
</div>