config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords"
  }

  resources :users, only: [ :show, :edit, :update ] do
    resources :cats, only: [ :new, :create, :edit, :update, :show, :destroy ]
  end

  resources :cats, only: [ :index ]

  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  post "logout", to: "sessions#destroy", as: "logout"

  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "terms_of_service" => "terms_of_service#index"
  get "privacy_policies" => "privacy_policies#index"
  get "images/ogp.png", to: "images#ogp", as: "images_ogp"



  resources :feeding_calculation, only: [ :new ] do
    collection do
      post :calculate # 計算を行う
      post :save      # 結果を保存 (ログインユーザーのみ)
      get :calculate
    end
    member do
      delete :destroy
    end
  end

  resources :brands, only: [ :index, :show ] do
    member do
      get :foods # /brands/:id/foods に対応
    end

    collection do
      get :autocomplete
    end
  end



  resources :foods, only: [ :show ] do
    collection do
      get :bookmarks
    end

    resources :reviews, only: [ :new, :create ]
  end

  # resources :reviews, only: [ :index ]

  resources :bookmarks, only: [ :create, :destroy ]

  resources :contacts, only: [ :new, :create ] do
    collection do
      match "confirm", via: [ :get, :post ]
      post "back"
      get "done"
    end
  end

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :brand
  has_many :reviews, dependent: :destroy
  has_many :feeding_calculation
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_users, through: :bookmarks, source: :user

  # Ransackで検索可能な属性を明示的に定義
  def self.ransackable_attributes(auth_object = nil)
    [ "name", "external_url", "brand_id", "created_at", "updated_at" ]
  end

  # Ransackで関連を検索可能にするためのメソッド
  def self.ransackable_associations(auth_object = nil)
    [ "brand", "reviews" ]
  end

  def average_rating
    reviews.average(:rating)&.round(1) || 0 # nilの場合は0を返す
  end

  def total_reviews
    reviews.count
  end

  def rating_percentage
    total = total_reviews.to_f
    return { 1 => 0, 2 => 0, 3 => 0, 4 => 0, 5 => 0 } if total.zero?

    (1..5).each_with_object({}) do |star, percentages|
      percentages[star] = ((reviews.where(rating: star).count / total) * 100).round
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def show
    @food = Food.find(params[:id])
    @reviews = @food.reviews.includes(:user).order(created_at: :desc)
    @average_rating = @food.average_rating
    @total_reviews = @food.total_reviews
    @rating_percentage = @food.rating_percentage
  end

  def bookmarks
    @bookmark_foods = current_user.bookmark_foods.includes(:brand).order(created_at: :desc)
  end
end

app/views/foods/_bookmark.html.erb
<%= link_to bookmarks_path(food_id: food.id), id: "bookmark-button-for-food-#{food.id}", data: { "turbo_method": :post } do %>
  <span class="material-icons text-default"style="font-size: 40px;">bookmark_border</span>
<% end %>

app/views/foods/_bookmark_buttons.html.erb
<div class='ms-auto'>
  <% if user_signed_in? %>
    <% if current_user.bookmark?(food) %>
      <%= render "unbookmark", { food: food } %>
    <% else %>
      <%= render "bookmark", { food: food } %>
    <% end %>
  <% end %>
</div>

app/views/foods/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(food_id: food.id).id), id: "unbookmark-button-for-food-#{food.id}", data: { "turbo_method": :delete } do %>
  <span class="material-icons text-default"style="font-size: 40px;">bookmark</span>
<% end %>

app/views/foods/bookmarks.html.erb
<div class="container mx-auto mb-8">
  <h1 class="text-center mb-6 mt-2 text-3xl text-default">ブックマーク一覧</h1>
  <% if @bookmark_foods.present? %>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
      <% @bookmark_foods.each do |food| %>
        <%= render 'shared/food_card', food: food %>
      <% end %>
    </div>
  <% else %>
    <p class="text-center">ブックマークされたフードはありません。</p>
  <% end %>
</div>

app/views/foods/show.html.erb
<h1 class="text-center mb-6 mt-2 text-2xl text-default"><%= t('.title') %></h1>
<div class="flex items-center justify-center">
  <div class="w-full max-w-2xl items-center my-2  mx-2 bg-white p-6 rounded-lg shadow-md">
    <div class="flex items-center justify-center mb-2 w-full">
      <!-- food.name -->
      <p class="text-xl text-gray-900 text-center break-words whitespace-normal px-4 flex-1">
        <%= @food.name %>
      </p>

      <!-- ブックマークボタン -->
      <div class="flex-shrink-0">
        <%= render 'bookmark_buttons', { food: @food } %>
      </div>
    </div>

    <p class="text-lg text-gray-700 text-center"><%= @food.brand.name %></p>

    <% unless user_signed_in? %>
      <p class="text-red-500 text-sm text-center mt-4">ログインユーザーはブックマーク、レビュー投稿できます</p>
    <% end %>


    <div class="flex justify-between my-6">
      <div class="flex-1 flex justify-center">
        <%= link_to safe_external_url(@food.external_url), class: "flex items-center text-blue-500 text-lg", target: "_blank", rel: "noopener" do %>
          <span class="material-icons">open_in_new</span>
          <p class="hover:underline">商品ページはこちら</p>
        <% end %>
      </div>
    </div>


    <div class="flex flex-col items-center">
      <div class="flex flex-row">
        <% 5.times do |i| %>
          <% if i < @average_rating.to_i %>
            <svg class="w-5 h-5 text-yellow-400 mx-0.5" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
              <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
            </svg>
          <% else %>
            <svg class="w-5 h-5 text-gray-300 mx-0.5" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
              <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
            </svg>
          <% end %>
        <% end %>
        <p class="text-sm font-medium text-gray-600 mt-1 ml-2"><%= @average_rating %> / 5</p>
    
      </div>
      <p class="text-sm font-medium text-gray-500"><%= @total_reviews %> 件の評価</p>

    </div>

    <div class="mb-8">
      <% @rating_percentage.each do |star, percentage| %>
        <div class="flex items-center mt-3">
          <span class="text-sm font-medium text-gray-700 w-10 text-right"><%= star %>★</span>
          <div class="w-2/4 h-5 mx-4 bg-gray-200 rounded overflow-hidden">
            <div class="h-full bg-yellow-400" style="width: <%= percentage %>%"></div>
          </div>
          <span class="text-sm font-medium text-gray-600"><%= percentage %>%</span>
        </div>
      <% end %>
    </div>

    <div class="mt-4 mb-10 flex justify-between items-center text-default hover:opacity-50">
      <%= link_to brands_path, class:"flex justify-start" do  %>
        <span class="material-icons "style="font-size: 40px;">reply</span>
        <p class="mt-3">フード一覧に戻る</P>
      <% end %>
    </div>

    <div class="flex justify-between mb-4 border-t border-gray-300">
      <h2 class="text-xl text-default mt-4">みんなのレビュー</h2>
      <%= link_to "レビュー投稿", new_food_review_path(@food.id), class: "px-4 py-2 mt-2 text-white bg-default rounded-md hover:opacity-50" %>
    </div>
    <% if @reviews.any? %>
      <% @reviews.each do |review| %>
        <div class="p-4 bg-white border border-gray-200 rounded-lg shadow-md mb-4">
          <div class="flex items-center">
            <%= link_to image_tag(review.user.profile.attached? ? review.user.profile : 'account.png', class: 'w-10 h-10 rounded-full object-cover border border-default mr-3'), user_path(review.user) %>
            <%= link_to review.user.name, user_path(review.user), class: 'text-lg text-gray-800' %>
          </div>

          <div class="flex items-center mt-2 mb-2">
            <% 5.times do |i| %>
              <% if i < review.rating %>
                <svg class="w-5 h-5 text-yellow-400" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                  <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                </svg>
              <% else %>
                <svg class="w-5 h-5 text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                  <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                </svg>
              <% end %>
            <% end %>
          </div>

          <p class="text-gray-700 break-words"><%= review.comment %></p>
          <p class="text-sm text-gray-500 mt-2">投稿日: <%= review.created_at.strftime('%Y-%m-%d %H:%M') %></p>  
        </div>
      <% end %>
    <% else %>
      <p class="flex justify-center text-gray-500">まだレビューがありません。</p>
    <% end %>
  </div>
</div>